# Generated by Django 3.2.9 on 2024-03-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('pray_name', models.CharField(default='', max_length=225)),
                ('info', models.CharField(max_length=2010)),
                ('english_name', models.CharField(default='', max_length=225)),
                ('english_info', models.CharField(default='', max_length=2010)),
                ('img', models.CharField(max_length=2010)),
                ('url', models.CharField(max_length=2010)),
            ],
        ),
    ]
